(function(){
  "use strict";

  var ICONS = ['award','target','code','hf','briefcase','star','message','globe','waveform','check','layers','heart','train','leaf','flask','mic'];
  var $ = function(id){ return document.getElementById(id); };

  /* ---------------- Profile picture ---------------- */
  var profileSeed = (typeof PROFILE !== 'undefined') ? PROFILE : { image: '', initials: 'JS' };
  var profileState = { image: profileSeed.image || '', initials: profileSeed.initials || 'JS' };

  function renderProfileAvatar(){
    var el = $('profileAvatarPreview');
    if(profileState.image){
      el.innerHTML = '<img src="' + profileState.image + '" alt="Profile preview">';
    } else {
      el.textContent = profileState.initials;
    }
  }
  renderProfileAvatar();

  $('profileUpload').addEventListener('change', function(e){
    var file = e.target.files[0];
    if(!file) return;
    if(file.size > 3 * 1024 * 1024){
      showToast('That photo is quite large (' + Math.round(file.size/1024) + ' KB) — a smaller image keeps the site fast.');
    }
    var reader = new FileReader();
    reader.onload = function(){
      profileState.image = reader.result;
      renderProfileAvatar();
      $('profileExportStatus').textContent = 'Unsaved changes — click Export when ready.';
      $('profileExportStatus').classList.remove('ok');
    };
    reader.readAsDataURL(file);
  });

  $('profileRemoveBtn').addEventListener('click', function(){
    profileState.image = '';
    $('profileUpload').value = '';
    renderProfileAvatar();
    $('profileExportStatus').textContent = 'Unsaved changes — click Export when ready.';
    $('profileExportStatus').classList.remove('ok');
  });

  $('profileExportBtn').addEventListener('click', function(){
    var header =
'/*\n' +
' * PROFILE DATA\n' +
' * ------------\n' +
' * Controls the small avatar in the top-left of the nav bar, next to your\n' +
' * name. Leave `image` empty and it shows your initials instead (the\n' +
' * default gold/terracotta "JS" mark).\n' +
' *\n' +
' * TO ADD OR CHANGE YOUR PROFILE PICTURE:\n' +
' *   Open admin.html — the "Profile Picture" panel at the top lets you\n' +
' *   upload a photo and exports an updated copy of this exact file.\n' +
' *   Download it and replace this file, then push to GitHub.\n' +
' *\n' +
' * FIELD REFERENCE:\n' +
' *   image    (optional) — path to an image ("assets/profile.jpg") or a\n' +
' *                          data: URI (what admin.html produces on upload)\n' +
' *                          leave as "" to show initials instead\n' +
' *   initials (optional) — fallback text shown when no image is set\n' +
' *\n' +
' * Regenerated by admin.html on ' + new Date().toISOString().slice(0,10) + '\n' +
' */\n\n';
    var body = 'const PROFILE = ' + JSON.stringify(profileState, null, 2) + ';\n\n' +
      '// Support both browser <script> usage and module usage (for admin.html)\n' +
      'if (typeof module !== "undefined" && module.exports) {\n' +
      '  module.exports = PROFILE;\n' +
      '}\n';
    var text = header + body;
    var blob = new Blob([text], { type: 'text/javascript' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'profile-data.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast('Downloaded profile-data.js — replace the file in your project and push.');
    $('profileExportStatus').textContent = 'Exported just now. Remember to replace js/profile-data.js in your repo.';
    $('profileExportStatus').classList.add('ok');
  });

  // Seed state from achievements-data.js if it loaded, else start empty.
  var seed = (typeof ACHIEVEMENTS !== 'undefined') ? ACHIEVEMENTS : [];
  var state = JSON.parse(JSON.stringify(seed)); // deep copy — never mutate the seed
  var editingIndex = null;
  var pendingCertDataUri = null;
  var pendingCertName = null;

  /* ---------------- Icon select population ---------------- */
  var fIcon = $('fIcon');
  ICONS.forEach(function(name){
    var opt = document.createElement('option');
    opt.value = name;
    opt.textContent = name;
    fIcon.appendChild(opt);
  });
  fIcon.addEventListener('change', updateIconPreview);
  function updateIconPreview(){
    $('fIconPreview').innerHTML = '<svg><use href="#icon-' + fIcon.value + '"></use></svg>';
  }
  updateIconPreview();

  /* ---------------- Certificate upload ---------------- */
  $('fCertUpload').addEventListener('change', function(e){
    var file = e.target.files[0];
    if(!file) return;
    if(file.size > 3 * 1024 * 1024){
      showToast('That image is quite large (' + Math.round(file.size/1024) + ' KB). Consider a smaller file so the site stays fast.');
    }
    var reader = new FileReader();
    reader.onload = function(){
      pendingCertDataUri = reader.result;
      pendingCertName = file.name;
      $('fCertPath').value = '';
      $('fCertPath').disabled = true;
      $('certThumbImg').src = pendingCertDataUri;
      $('certThumbName').textContent = file.name + ' (' + Math.round(file.size/1024) + ' KB) — will be embedded on export';
      $('certThumb').classList.add('show');
    };
    reader.readAsDataURL(file);
  });
  $('certThumbClear').addEventListener('click', function(){
    pendingCertDataUri = null;
    pendingCertName = null;
    $('fCertUpload').value = '';
    $('fCertPath').disabled = false;
    $('certThumb').classList.remove('show');
  });

  /* ---------------- Form submit (add or save edit) ---------------- */
  $('admForm').addEventListener('submit', function(e){
    e.preventDefault();
    var title = $('fTitle').value.trim();
    var issuer = $('fIssuer').value.trim();
    if(!title || !issuer){ return; }

    var entry = { title: title, issuer: issuer };
    var date = $('fDate').value.trim();
    if(date) entry.date = date;
    entry.icon = fIcon.value || 'award';
    var verify = $('fVerify').value.trim();
    if(verify) entry.verify = verify;
    var cert = pendingCertDataUri || $('fCertPath').value.trim();
    if(cert) entry.cert = cert;

    if(editingIndex !== null){
      state[editingIndex] = entry;
      showToast('Saved changes to "' + title + '"');
    } else {
      state.push(entry);
      showToast('Added "' + title + '"');
    }
    resetForm();
    renderList();
    markDirty();
  });

  $('cancelEditBtn').addEventListener('click', resetForm);

  function resetForm(){
    editingIndex = null;
    $('admForm').reset();
    pendingCertDataUri = null;
    pendingCertName = null;
    $('fCertPath').disabled = false;
    $('certThumb').classList.remove('show');
    fIcon.value = 'award';
    updateIconPreview();
    $('formTitle').textContent = 'Add an achievement';
    $('submitBtn').textContent = 'Add achievement';
    $('cancelEditBtn').style.display = 'none';
  }

  function editEntry(i){
    var a = state[i];
    editingIndex = i;
    $('fTitle').value = a.title || '';
    $('fIssuer').value = a.issuer || '';
    $('fDate').value = a.date || '';
    fIcon.value = a.icon || 'award';
    updateIconPreview();
    $('fVerify').value = a.verify || '';
    pendingCertDataUri = null;
    pendingCertName = null;
    $('fCertUpload').value = '';
    $('fCertPath').disabled = false;
    if(a.cert && a.cert.indexOf('data:') === 0){
      pendingCertDataUri = a.cert;
      $('fCertPath').disabled = true;
      $('certThumbImg').src = a.cert;
      $('certThumbName').textContent = 'Existing embedded image — will be kept unless you replace it';
      $('certThumb').classList.add('show');
    } else {
      $('fCertPath').value = a.cert || '';
      $('certThumb').classList.remove('show');
    }
    $('formTitle').textContent = 'Edit achievement';
    $('submitBtn').textContent = 'Save changes';
    $('cancelEditBtn').style.display = 'inline-flex';
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  function deleteEntry(i){
    if(!confirm('Remove "' + state[i].title + '" from the list?')) return;
    state.splice(i, 1);
    if(editingIndex === i) resetForm();
    renderList();
    markDirty();
  }

  function moveEntry(i, dir){
    var j = i + dir;
    if(j < 0 || j >= state.length) return;
    var tmp = state[i]; state[i] = state[j]; state[j] = tmp;
    renderList();
    markDirty();
  }

  /* ---------------- Render list (reuses site's .ach-card styling) ---------------- */
  function renderList(){
    var list = $('admList');
    var empty = $('admEmpty');
    list.innerHTML = '';
    $('admCount').textContent = state.length + (state.length === 1 ? ' item' : ' items');
    empty.style.display = state.length ? 'none' : 'block';

    state.forEach(function(a, i){
      var card = document.createElement('div');
      card.className = 'ach-card adm-card';

      var ico = document.createElement('div');
      ico.className = 'ach-ico';
      ico.innerHTML = '<svg><use href="#icon-' + (a.icon || 'award') + '"></use></svg>';
      card.appendChild(ico);

      var body = document.createElement('div');
      body.style.flex = '1';
      body.style.minWidth = '0';

      var h4 = document.createElement('h4');
      h4.textContent = a.title;
      body.appendChild(h4);

      var meta = document.createElement('span');
      meta.className = 'ach-meta';
      meta.textContent = a.issuer + (a.date ? ' · ' + a.date : '');
      body.appendChild(meta);

      var badges = [];
      if(a.cert) badges.push('has certificate image');
      if(a.verify) badges.push('has verify link');
      if(badges.length){
        var b = document.createElement('span');
        b.className = 'ach-meta';
        b.style.color = 'var(--teal-soft)';
        b.textContent = badges.join(' · ');
        body.appendChild(b);
      }

      var controls = document.createElement('div');
      controls.className = 'adm-card-controls';
      controls.innerHTML =
        '<button type="button" data-act="up" ' + (i === 0 ? 'disabled style="opacity:.35"' : '') + '>&uarr; Up</button>' +
        '<button type="button" data-act="down" ' + (i === state.length - 1 ? 'disabled style="opacity:.35"' : '') + '>&darr; Down</button>' +
        '<button type="button" data-act="edit">Edit</button>' +
        '<button type="button" data-act="del" class="danger">Delete</button>';
      controls.querySelector('[data-act=up]').addEventListener('click', function(){ moveEntry(i, -1); });
      controls.querySelector('[data-act=down]').addEventListener('click', function(){ moveEntry(i, 1); });
      controls.querySelector('[data-act=edit]').addEventListener('click', function(){ editEntry(i); });
      controls.querySelector('[data-act=del]').addEventListener('click', function(){ deleteEntry(i); });
      body.appendChild(controls);

      card.appendChild(body);
      list.appendChild(card);
    });
  }

  /* ---------------- Export ---------------- */
  function buildFileText(){
    var header =
'/*\n' +
' * ACHIEVEMENTS DATA\n' +
' * ------------------\n' +
' * This is the single source of truth for the "Achievements & certifications"\n' +
' * section on the site. The site reads this file and builds the cards\n' +
' * automatically — you never need to touch index.html to add one.\n' +
' *\n' +
' * TO ADD A NEW ACHIEVEMENT BY HAND:\n' +
' *   Copy one of the objects below, paste it into the array, and edit the\n' +
' *   fields. Then save this file and refresh the page (or push to GitHub).\n' +
' *\n' +
' * TO ADD ONE WITHOUT EDITING CODE:\n' +
' *   Open admin.html in a browser. It gives you a form, and an "Export"\n' +
' *   button that generates an updated copy of this exact file for you to\n' +
' *   download and commit to your repo. See README.md for details.\n' +
' *\n' +
' * FIELD REFERENCE:\n' +
' *   title    (required) — the achievement or certificate name\n' +
' *   issuer   (required) — who issued it / where it happened\n' +
' *   date     (optional) — a short display string, e.g. "May 2026"\n' +
' *   icon     (required) — one of: award, target, code, hf, briefcase,\n' +
' *                          star, message, globe, waveform, check, layers,\n' +
' *                          heart, train, leaf, flask, mic\n' +
' *   verify   (optional) — a URL where anyone can verify the credential\n' +
' *   cert     (optional) — path to a certificate image, e.g.\n' +
' *                          "assets/certificates/yourfile.jpg"\n' +
' *                          (or a data: URI if embedded via admin.html)\n' +
' *                          shows a "View certificate" button that opens\n' +
' *                          the image in a lightbox\n' +
' *\n' +
' * Regenerated by admin.html on ' + new Date().toISOString().slice(0,10) + '\n' +
' */\n\n';
    var body = 'const ACHIEVEMENTS = ' + JSON.stringify(state, null, 2) + ';\n\n' +
      '// Support both browser <script> usage and module usage (for admin.html)\n' +
      'if (typeof module !== "undefined" && module.exports) {\n' +
      '  module.exports = ACHIEVEMENTS;\n' +
      '}\n';
    return header + body;
  }

  $('exportBtn').addEventListener('click', function(){
    var text = buildFileText();
    var blob = new Blob([text], { type: 'text/javascript' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url;
    a.download = 'achievements-data.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast('Downloaded achievements-data.js — replace the file in your project and push.');
    $('exportStatus').textContent = 'Exported just now. Remember to replace js/achievements-data.js in your repo.';
    $('exportStatus').classList.add('ok');
  });

  $('copyBtn').addEventListener('click', function(){
    var text = buildFileText();
    if(navigator.clipboard){
      navigator.clipboard.writeText(text).then(function(){
        showToast('Code copied — paste it into js/achievements-data.js');
      });
    }
  });

  $('resetBtn').addEventListener('click', function(){
    if(!confirm('Discard all changes in this session and reload the saved list?')) return;
    state = JSON.parse(JSON.stringify(seed));
    resetForm();
    renderList();
    $('exportStatus').textContent = 'Changes stay in this browser tab until you export.';
    $('exportStatus').classList.remove('ok');
  });

  function markDirty(){
    $('exportStatus').textContent = 'Unsaved changes — click Export when ready.';
    $('exportStatus').classList.remove('ok');
  }

  /* ---------------- Toast ---------------- */
  var toastTimer = null;
  function showToast(msg){
    var t = $('toast');
    t.textContent = msg;
    t.classList.add('show');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function(){ t.classList.remove('show'); }, 3200);
  }

  /* ---------------- Warn before leaving with unsaved work ---------------- */
  var hasUnsavedWork = false;
  document.addEventListener('input', function(){ hasUnsavedWork = true; });

  renderList();

  if(!seed.length){
    showToast('Could not load existing achievements — starting from an empty list. Try running this via a local server if that seems wrong.');
  }
})();
